const fs = require('fs')
const path = require('path')
const { nanoid } = require('nanoid')


/* {
  "name": "product one (1)",
  "price": 32,
  "rating": 5,
  "summary" : "short summary",
  "description": "long description",
  "coverPhoto" : {
    "public_id" : "5485465465q465465r456a654f84654",
    "secure_url": "data:image/jpg;base64,imagename.jpg"
  },
  "images" : [
    {
      "public_id" : "5485465465q465465r456a654f84654",
      "secure_url": "data:image/png;base64,imagename.jpg"
    },
    {
      "public_id" : "5485465465q465465r456a654f84654",
      "secure_url": "data:application/pdf;base64,imagename.jpg"
    },
    {
      "public_id" : "5485465465q465465r456a654f84654",
      "url": "imagename.jpg"
    }
  ]
} */




const isObject = (item, imageField, destination) => {

  // check imageable field is an object and that object has property: { ..., secure_url: '' } <= imageField
  if( item.constructor !== Object || item.constructor === Object && !(imageField in item) ) return item

  // check imageField is base64 String.
  if( !item[imageField].startsWith('data:') ) return item

  const [ metadata, base64 ] = item[imageField].split(';base64,')     // => [ 'data:image/jpg', 'imagename.jpg' ]
  const ext = metadata.split('/').pop()

  // const filename = Date.now() + Math.round(Math.random() * 1000)
  // const url = path.resolve(__dirname, '../', 'static/images/reviews', `${filename}.${ext}`)
  const filename = nanoid()
  const url = path.resolve(destination, `${filename}.${ext}`)


  const fileBuffer = Buffer.from(base64, 'base64')
  fs.writeFileSync(url, fileBuffer)
  

  console.log(ext)

	return { 
    ...item, 
    public_id: filename,
    [imageField]: url.split('/server').pop()    // give static path of express server.
  }
}



/* To handle Image must follor bettow Rules:
**  1. Make sure image field is an Object:  For now we validate as object
**  2. Image field name must be passed via middleware or default is 'secure_url
**   . public_id will be auto generated by server
*/
const imageHandler = (destination, imageField='secure_url') => (req, res, next) => {

  const body = req.body

  Object.keys(body).forEach(field => {
    let item = body[field]

    if(Array.isArray(item)) item.forEach( (obj, index ) => item[index] = isObject(obj, imageField, destination) )
    body[field] = isObject(item, imageField, destination)
  })

  next()
}
module.exports = imageHandler